### ISSUE TITLE
How do you update your pacakges?

### ISSUE THREAD

**Issue by uwemolnar** [andreasmalta/choco_packages#1]
Hi Andreas,

may i ask how you update your choco-packages? Did you also automate this process?  

Thanks for your answer!
Best wishes

**Comment by andreasmalta** [comment]
I wish I knew how to automate :-)

Best regards, 
Andreas

**Comment by uwemolnar** [comment]
Thanks for your answer. We use a combination of GitHub Actions and AU-Modul ;)

https://github.com/majkinetor/au

I think many package-owners do it this way. Maybe also something for your packages.

**Comment by andreasmalta** [comment]
i tested some of my packages but it was not so easy to track changes for many of them...
