### ISSUE TITLE
Autocad install via chocolatey - Succesfull install "hangs"

### ISSUE THREAD

**Issue by NekoJonez** [andreasmalta/choco_packages#5]
I'm using a script to install Autocad on my student PC's. But after that, I install other chocolatey apps. But, all the time after Autocad is installed, it hangs. My script refuses to continue after that. 

Also, the same thing happens if I just write "choco install autocad" in my terminal, I have the same issue.

**Comment by andreasmalta** [comment]
Hi, I tested an installation on a fresh machine, and the script still works
for me.
Someone needs to have a closer look at your environment I think...
Br, Andreas

**Comment by NekoJonez** [comment]
Yes, the script works and the install works... But, can you write another command when it finished?

**Comment by andreasmalta** [comment]
what command would you lite to add?
since it is a community package i have to be careful what i put in the
script of course.
or you can run it after your choco command?

**Comment by NekoJonez** [comment]
I run it after the choco command. It's a part of a multi install script via choco
